### ISSUE TITLE
Could someone fake "User" Cookie in browser to be authenticated?

### ISSUE THREAD

**Issue by flexlee** [luisrudge/next.js-auth0#28]
Authentication status is determined by
```
const loggedUser = process.browser ? getUserFromLocalCookie() : getUserFromServerCookie(ctx.req)
const isAuthenticated = !!loggedUser
```

Could someone edit the browser cookie and gain "Authenticated" status?

**Comment by luisrudge** [comment]
they can, but they'll get a fake access_token and a fake id_token, so when you call your backend to fetch some data, you'll validate the tokens and reject the request

**Comment by flexlee** [comment]
@luisrudge thanks for the quick response. But if they can fake authentication status, they can open securePage at least on the client side, even though they can't retrieve data from the backend? Maybe on the client side, we should only grant "Authenticated"status after validating access_token and id_token upon logging into auth0.

**Comment by luisrudge** [comment]
you're right and that's true about every js framework, considering the page is somewhere in the js bundle, right? that's why you have to secure your backend. If you're using a traditional web server that renders everything in the server, then you can do what you said (don't show anything if you don't have the cookie).
