### ISSUE TITLE
Token validation

### ISSUE THREAD

**Issue by thierryMic** [luisrudge/next.js-auth0#34]
This is more of a question than an issue but should the token be validated in the componentDidMount function of signed-in.js?

I just tested the app as follows and got manged to get in:
1.  Installed the cookie add-in for Chrome 
2.  Added random values for user and secret
3.  Copied and pasted a random but valid token from [jwt.io](https://jwt.io/)
4.  Visited /secret and I could see the secret div and links

![image](https://user-images.githubusercontent.com/21054294/42985965-03b7e638-8c37-11e8-843e-96b0ede4a83c.png)

**Comment by luisrudge** [comment]
You can't validate tokens in the client because you need the client_secret to do that. The client_secret *should not* be leaked, so it must be used only in your backend. This means that you can see the page, yes, but your API would validate the token and don't return the actual data that shows up in the page.

**Comment by thierryMic** [comment]
That makes sense, thank you.
