### ISSUE TITLE
No CSRF check

### ISSUE THREAD

**Issue by sedubois** [luisrudge/next.js-auth0#5]
It would be better to pass a state to Auth0 and check that it is the same in the response to avoid CSRF. For example as I did [here](https://github.com/sedubois/belong/blob/master/app/containers/Login/lib.js#L23) (and I'll do it on my [Next](https://github.com/sedubois/realate) stack when I can).

**Comment by luisrudge** [comment]
I'm not an expert about CSRF, so I have two questions:

1 - how would you exploit this app using CSRF if you can't send POST requests to it?
2 - what is this `state.secret` object you're sending to the lock component?

**Comment by sedubois** [comment]
1. I'm not an expert at all either... But AFAIK the auth flow is done through GET requests, that's how your callback route (that you call `auth/signed-in` although the user is not yet signed in) gets triggered by the Auth0 server.
2. it's just a random string (check the `createNonce` method in my example)

**Comment by luisrudge** [comment]
1 - ahh, right.. so you can create a forged but valid jwt token and pass directly to that route and still be signed in, right? but if you intercept the auth0 request with chrome dev tools, you can easily get the `secret` value as well, right?
2 - cool, but where do you check that?

**Comment by sedubois** [comment]
1. I'm no expert, we're in the same boat 😉 
2. in auth/sign-in you need to create and store the secret in localStorage and pass it to lock, then in auth/signed-in (which I call auth/callback) you get from localstorage and compare. One thing missing in your signed-in route is that you're not parsing the result with Auth0Lock but using your own custom logic (you decode the jwt manually etc). I suggest you use the Aut0 API (check my code).

**Comment by sedubois** [comment]
How would an attacker access your localStorage?

**Comment by luisrudge** [comment]
oh, right. not a CSRF attack, but a token forgery attack, where someone tries to access `/auth/signed-in#id_token={fakeToken}`.
Having the extra `secret` parameter doesn't help a lot, since you can open the lock, get the secret from the request and forge your token+secret in the `/auth/signed-in#id_token={fakeToken}` route anyway.

**Comment by sedubois** [comment]
I don't understand how someone would be able to steal your identity that way by listening to your traffic. The only non-encrypted secret stays on your machine. Anyway I gave this advice because that's what Auth0 advises to do, quite simply.

**Comment by luisrudge** [comment]
Right, I just read the auth0 guideline and with your explanation backing it up, it makes sense now. I'll implement that as well. Thanks again for you patience ❤️

**Comment by sedubois** [comment]
Sure! it's easier when trying to figure things out together 😊

**Comment by luisrudge** [comment]
fixed here https://github.com/luisrudge/next.js-auth0/commit/5693936c29e9654b1e9c5899e610b84eef88538d

Thanks again @sedubois

**Comment by ndreckshage** [comment]
I think this extra check is fine to leave in, but it doesn't prevent CSRF. It might be good to clarify in README or something, as I was a little confused by this addition reading through code.

What this seems to prevent: someone spoofing a JWT which might give them the ability to show / hide certain routes (etc) based on your `isAuthenticated` check. Fine to leave in if you want to prevent access to the JS (not API) or certain application routes though! But for my own application though, I wouldn't be worried about this at all.

For most Auth0 apps, CSRF a non-issue. Good resource - https://auth0.com/blog/cookies-vs-tokens-definitive-guide/

But since Next is universal and cookies are necessary (so that server side `getInitialProps` can pass JWT to API), I wanted to be careful. But after thinking about it, I still don't think CSRF much of an issue.

I think the only CSRF risk is if someone (for example) has an attempted malicious img tag on their site (`<img src="mysite.com/some-get?do_something_bad=true" />`). In this case a logged in user would unsuspectingly hit a `GET` route, triggering an API `GET` in `getInitialProps`. But this is a risk for standard sites that use cookie based sessions.

Since most Next setups (I believe) interact with an API on a different subdomain, and that the API's typically use Headers (not cookies), and then validate the JWT, I think the CSRF risk is still pretty minimal like in the linked Auth0 doc.

I could see CSRF being an issue if someone uses cookies on API server, and (1) NGINX rewrites api.domain.com to app.domain.com/api/ or something, or (2) uses wildcard cookies from app, matching, api and www servers.

But no matter what...to prevent CSRF, a token would need to be generated + encrypted server side, and included with `POST` requests. So I think some of this work in here might be a bit misleading to new comers interested in Auth0 / Next!

**Comment by luisrudge** [comment]
Thanks for the insights @ndreckshage, I added a comment to the commit [here](https://github.com/luisrudge/next.js-auth0/commit/5693936c29e9654b1e9c5899e610b84eef88538d#commitcomment-19972922)
